services:
  app:
    build:
      context: ../../../
      dockerfile: deploy/ssr/Dockerfile
    deploy:
      replicas: 3
    networks:
      - album-network

  nginx-lb:
    build:
      context: ../../ssr
      dockerfile: Dockerfile.lb
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - album-network

networks:
  album-network:
    driver: bridge
